name: Upload charm

on:
  push:
    branches:
      - "main"

jobs:
  upload:
    runs-on: ubuntu-20.04
    name: Charmhub upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Wait for integration tests to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: main
          check-name: "Integration tests"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 60

      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@2.2.5
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@2.2.5
        id: channel

      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.2.5
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"

      - name: Chmod charmcraft logs
        if: steps.upload.conclusion == 'failure'
        run: |
          sudo chmod -R 777 /root/snap/charmcraft/common/cache/charmcraft/log/ 

      - name: Archive charmcraft logs
        if: steps.upload.conclusion == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: charmcraft-upload-logs
          path: /root/snap/charmcraft/common/cache/charmcraft/log/*.log