name: Upload charm

on:
  push:
    branches:
      - "main"

jobs:
  upload:
    runs-on: ubuntu-20.04
    name: Charmhub upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@2.0.0-rc
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Select charmhub channel
        uses: canonical/charming-actions/channel@2.0.0-rc
        id: channel

      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@2.0.0-rc
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"
